
const DATA_VSCODE = [
    // --- تحرير الكود (Code Editing) ---
    { id: "vs01", type: "shortcut", shortcut: "Ctrl + D", arabicName: "تحديد الكلمة التالية", englishName: "Select Next Occurrence", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "تحديد النص المتطابق التالي لإجراء تعديلات متعددة.", keywords: ["select", "multi", "next"] },
    { id: "vs02", type: "shortcut", shortcut: "Ctrl + Shift + L", arabicName: "تحديد كل التطابقات", englishName: "Select All Occurrences", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "تحديد جميع مواضع الكلمة في الملف.", keywords: ["select", "all", "match"] },
    { id: "vs03", type: "shortcut", shortcut: "Alt + ↑ / ↓", arabicName: "تحريك السطر", englishName: "Move Line Up/Down", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "نقل السطر الحالي أعلى أو أسفل.", keywords: ["move", "line", "swap"] },
    { id: "vs04", type: "shortcut", shortcut: "Shift + Alt + ↑ / ↓", arabicName: "تكرار السطر", englishName: "Copy Line Up/Down", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "نسخ السطر الحالي لأعلى أو أسفل.", keywords: ["copy", "duplicate", "line"] },
    { id: "vs05", type: "shortcut", shortcut: "Ctrl + Shift + K", arabicName: "حذف السطر", englishName: "Delete Line", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "حذف السطر الحالي بالكامل.", keywords: ["delete", "line", "remove"] },
    { id: "vs06", type: "shortcut", shortcut: "Ctrl + Enter", arabicName: "سطر جديد أدناه", englishName: "Insert Line Below", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إدراج سطر جديد أسفل السطر الحالي.", keywords: ["new", "line", "below"] },
    { id: "vs07", type: "shortcut", shortcut: "Ctrl + Shift + Enter", arabicName: "سطر جديد أعلاه", englishName: "Insert Line Above", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إدراج سطر جديد فوق السطر الحالي.", keywords: ["new", "line", "above"] },
    { id: "vs08", type: "shortcut", shortcut: "Ctrl + /", arabicName: "تعليق / إلغاء تعليق", englishName: "Toggle Line Comment", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إضافة أو إزالة تعليق للسطر الحالي.", keywords: ["comment", "toggle"] },
    { id: "vs09", type: "shortcut", shortcut: "Shift + Alt + A", arabicName: "تعليق كتلة", englishName: "Block Comment", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إضافة تعليق للنص المحدد.", keywords: ["comment", "block"] },
    { id: "vs10", type: "shortcut", shortcut: "Ctrl + Shift + \\", arabicName: "القفز للقوس المطابق", englishName: "Jump to Bracket", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "الانتقال إلى القوس المفتوح أو المغلق المطابق.", keywords: ["bracket", "jump", "match"] },
    { id: "vs11", type: "shortcut", shortcut: "Tab", arabicName: "مسافة بادئة", englishName: "Indent", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إضافة مسافة بادئة للسطر أو النص المحدد.", keywords: ["indent", "tab"] },
    { id: "vs12", type: "shortcut", shortcut: "Shift + Tab", arabicName: "إزالة المسافة البادئة", englishName: "Outdent", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إزالة مسافة بادئة من السطر.", keywords: ["outdent", "remove", "indent"] },
    { id: "vs13", type: "shortcut", shortcut: "Ctrl + ]", arabicName: "إضافة مسافة بادئة", englishName: "Indent Line", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إضافة مسافة بادئة للسطر الحالي.", keywords: ["indent", "line"] },
    { id: "vs14", type: "shortcut", shortcut: "Ctrl + [", arabicName: "إزالة مسافة بادئة", englishName: "Outdent Line", program: "VS Code", category: "VS Code", subCategory: "التحرير", description: "إزالة مسافة بادئة من السطر الحالي.", keywords: ["outdent", "line"] },

    // --- المؤشرات المتعددة والتحديد (Multi-Cursor & Selection) ---
    { id: "vs15", type: "shortcut", shortcut: "Alt + Click", arabicName: "مؤشر إضافي", englishName: "Add Cursor", program: "VS Code", category: "VS Code", subCategory: "المؤشرات", description: "إضافة مؤشر كتابة في أي مكان بالنقر.", keywords: ["multi", "cursor", "add"] },
    { id: "vs16", type: "shortcut", shortcut: "Ctrl + Alt + ↑ / ↓", arabicName: "مؤشر أعلى / أسفل", englishName: "Add Cursor Above/Below", program: "VS Code", category: "VS Code", subCategory: "المؤشرات", description: "إضافة مؤشر في السطر فوق أو تحت.", keywords: ["cursor", "above", "below"] },
    { id: "vs17", type: "shortcut", shortcut: "Ctrl + A", arabicName: "تحديد الكل", englishName: "Select All", program: "VS Code", category: "VS Code", subCategory: "المؤشرات", description: "تحديد كامل محتوى الملف.", keywords: ["select", "all"] },
    { id: "vs18", type: "shortcut", shortcut: "Shift + Alt + →", arabicName: "توسيع التحديد", englishName: "Expand Selection", program: "VS Code", category: "VS Code", subCategory: "المؤشرات", description: "توسيع التحديد تدريجياً.", keywords: ["expand", "select"] },

    // --- التنقل (Navigation) ---
    { id: "vs19", type: "shortcut", shortcut: "Ctrl + P", arabicName: "فتح ملف بسرعة", englishName: "Quick Open File", program: "VS Code", category: "VS Code", subCategory: "التنقل", description: "البحث عن أي ملف في المشروع وفتحه.", keywords: ["open", "file", "quick"] },
    { id: "vs20", type: "shortcut", shortcut: "Ctrl + G", arabicName: "الانتقال لسطر", englishName: "Go to Line", program: "VS Code", category: "VS Code", subCategory: "التنقل", description: "الانتقال مباشرة لرقم سطر محدد.", keywords: ["goto", "line", "jump"] },
    { id: "vs21", type: "shortcut", shortcut: "Ctrl + Shift + O", arabicName: "الانتقال لرمز", englishName: "Go to Symbol", program: "VS Code", category: "VS Code", subCategory: "التنقل", description: "الانتقال لدالة أو متغير في الملف الحالي.", keywords: ["symbol", "function", "goto"] },
    { id: "vs22", type: "shortcut", shortcut: "F12", arabicName: "الذهاب للتعريف", englishName: "Go to Definition", program: "VS Code", category: "VS Code", subCategory: "التنقل", description: "الانتقال لمكان تعريف الدالة أو المتغير.", keywords: ["definition", "goto", "jump"] },
    { id: "vs23", type: "shortcut", shortcut: "Alt + ←", arabicName: "رجوع", englishName: "Go Back", program: "VS Code", category: "VS Code", subCategory: "التنقل", description: "العودة للموضع السابق في التاريخ.", keywords: ["back", "history", "navigate"] },
    { id: "vs24", type: "shortcut", shortcut: "Ctrl + Home / End", arabicName: "بداية / نهاية الملف", englishName: "Go to File Start/End", program: "VS Code", category: "VS Code", subCategory: "التنقل", description: "الانتقال لأول أو آخر سطر في الملف.", keywords: ["start", "end", "file"] },
    { id: "vs25", type: "shortcut", shortcut: "Ctrl + Tab", arabicName: "التبديل بين التبويبات", englishName: "Switch Tabs", program: "VS Code", category: "VS Code", subCategory: "التنقل", description: "التبديل بين الملفات المفتوحة.", keywords: ["tab", "switch", "file"] },

    // --- البحث والاستبدال (Search & Replace) ---
    { id: "vs26", type: "shortcut", shortcut: "Ctrl + F", arabicName: "بحث في الملف", englishName: "Find", program: "VS Code", category: "VS Code", subCategory: "البحث", description: "البحث عن نص في الملف الحالي.", keywords: ["find", "search"] },
    { id: "vs27", type: "shortcut", shortcut: "Ctrl + H", arabicName: "بحث واستبدال", englishName: "Find & Replace", program: "VS Code", category: "VS Code", subCategory: "البحث", description: "البحث عن نص واستبداله.", keywords: ["find", "replace"] },
    { id: "vs28", type: "shortcut", shortcut: "Ctrl + Shift + F", arabicName: "بحث في كل الملفات", englishName: "Search Across Files", program: "VS Code", category: "VS Code", subCategory: "البحث", description: "البحث في جميع ملفات المشروع.", keywords: ["search", "all", "project"] },

    // --- الواجهة والنافذة (UI & Window) ---
    { id: "vs29", type: "shortcut", shortcut: "Ctrl + `", arabicName: "فتح الطرفية", englishName: "Open Terminal", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "فتح Terminal مدمج داخل VS Code.", keywords: ["terminal", "console"] },
    { id: "vs30", type: "shortcut", shortcut: "Ctrl + B", arabicName: "إخفاء الشريط الجانبي", englishName: "Toggle Sidebar", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "إظهار أو إخفاء شريط المستعرض الجانبي.", keywords: ["sidebar", "hide", "panel"] },
    { id: "vs31", type: "shortcut", shortcut: "Ctrl + Shift + E", arabicName: "مستعرض الملفات", englishName: "Explorer Panel", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "فتح لوحة مستعرض الملفات.", keywords: ["explorer", "files", "panel"] },
    { id: "vs32", type: "shortcut", shortcut: "Ctrl + Shift + X", arabicName: "الإضافات", englishName: "Extensions Panel", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "فتح لوحة إدارة الإضافات.", keywords: ["extensions", "plugins", "marketplace"] },
    { id: "vs33", type: "shortcut", shortcut: "Ctrl + Shift + G", arabicName: "Source Control", englishName: "Source Control Panel", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "فتح لوحة Git والتحكم بالمصدر.", keywords: ["git", "source", "control"] },
    { id: "vs34", type: "shortcut", shortcut: "Ctrl + Shift + P", arabicName: "لوحة الأوامر", englishName: "Command Palette", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "الوصول لأي أمر في VS Code.", keywords: ["command", "palette"] },
    { id: "vs35", type: "shortcut", shortcut: "Ctrl + K Z", arabicName: "وضع Zen", englishName: "Zen Mode", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "تفعيل وضع الشاشة الكاملة بدون تشويش.", keywords: ["zen", "focus", "fullscreen"] },
    { id: "vs36", type: "shortcut", shortcut: "Ctrl + \\", arabicName: "تقسيم المحرر", englishName: "Split Editor", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "تقسيم نافذة التحرير لعمودين.", keywords: ["split", "editor", "side"] },
    { id: "vs37", type: "shortcut", shortcut: "Ctrl + W", arabicName: "إغلاق التبويب", englishName: "Close Tab", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "إغلاق الملف الحالي.", keywords: ["close", "tab"] },
    { id: "vs38", type: "shortcut", shortcut: "Ctrl + Shift + T", arabicName: "إعادة فتح التبويب", englishName: "Reopen Closed Tab", program: "VS Code", category: "VS Code", subCategory: "الواجهة", description: "إعادة فتح آخر تبويب تم إغلاقه.", keywords: ["reopen", "tab", "undo"] },

    // --- الكود والتنسيق (Code & Formatting) ---
    { id: "vs39", type: "shortcut", shortcut: "Shift + Alt + F", arabicName: "تنسيق الملف", englishName: "Format Document", program: "VS Code", category: "VS Code", subCategory: "التنسيق", description: "تنسيق كامل الملف تلقائياً.", keywords: ["format", "prettier", "auto"] },
    { id: "vs40", type: "shortcut", shortcut: "Ctrl + K Ctrl + F", arabicName: "تنسيق المحدد", englishName: "Format Selection", program: "VS Code", category: "VS Code", subCategory: "التنسيق", description: "تنسيق النص المحدد فقط.", keywords: ["format", "selection"] },
    { id: "vs41", type: "shortcut", shortcut: "F2", arabicName: "إعادة تسمية الرمز", englishName: "Rename Symbol", program: "VS Code", category: "VS Code", subCategory: "التنسيق", description: "إعادة تسمية متغير أو دالة في كل مكان.", keywords: ["rename", "refactor", "symbol"] },
    { id: "vs42", type: "shortcut", shortcut: "Ctrl + K Ctrl + C", arabicName: "إضافة تعليق لسطر", englishName: "Add Line Comment", program: "VS Code", category: "VS Code", subCategory: "التنسيق", description: "إضافة تعليق للسطر الحالي.", keywords: ["comment", "add"] },
    { id: "vs43", type: "shortcut", shortcut: "Ctrl + K Ctrl + 0", arabicName: "طي كل الكتل", englishName: "Fold All", program: "VS Code", category: "VS Code", subCategory: "التنسيق", description: "طي جميع مناطق الكود.", keywords: ["fold", "collapse", "all"] },
    { id: "vs44", type: "shortcut", shortcut: "Ctrl + K Ctrl + J", arabicName: "فتح كل الكتل", englishName: "Unfold All", program: "VS Code", category: "VS Code", subCategory: "التنسيق", description: "فتح جميع مناطق الكود المطوية.", keywords: ["unfold", "expand", "all"] },
    { id: "vs45", type: "shortcut", shortcut: "F5", arabicName: "تشغيل / تصحيح", englishName: "Start Debugging", program: "VS Code", category: "VS Code", subCategory: "التشغيل", description: "بدء جلسة التصحيح (Debug).", keywords: ["debug", "run", "start"] },
];
