
const DATA_AUTOCAD = [
    // --- أوامر الرسم (Draw Commands) ---
    { id: "ac01", type: "shortcut", shortcutType: "cmd", shortcut: "L → Enter", arabicName: "رسم خط", englishName: "Line", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "رسم خط مستقيم. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["line", "draw"] },
    { id: "ac02", type: "shortcut", shortcutType: "cmd", shortcut: "PL → Enter", arabicName: "رسم خط متعدد", englishName: "Polyline", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "رسم خطوط متعددة متصلة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["polyline", "poly", "draw"] },
    { id: "ac03", type: "shortcut", shortcutType: "cmd", shortcut: "C → Enter", arabicName: "رسم دائرة", englishName: "Circle", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "رسم دائرة بتحديد المركز والنصف قطر. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["circle", "draw"] },
    { id: "ac04", type: "shortcut", shortcutType: "cmd", shortcut: "A → Enter", arabicName: "رسم قوس", englishName: "Arc", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "رسم قوس دائري. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["arc", "curve", "draw"] },
    { id: "ac05", type: "shortcut", shortcutType: "cmd", shortcut: "REC → Enter", arabicName: "رسم مستطيل", englishName: "Rectangle", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "رسم مستطيل بنقطتين. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["rectangle", "rect", "draw"] },
    { id: "ac06", type: "shortcut", shortcutType: "cmd", shortcut: "EL → Enter", arabicName: "رسم قطع ناقص", englishName: "Ellipse", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "رسم شكل بيضاوي. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["ellipse", "oval", "draw"] },
    { id: "ac07", type: "shortcut", shortcutType: "cmd", shortcut: "SPL → Enter", arabicName: "رسم منحنى", englishName: "Spline", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "رسم منحنيات ناعمة مرنة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["spline", "curve", "smooth"] },
    { id: "ac08", type: "shortcut", shortcutType: "cmd", shortcut: "H → Enter", arabicName: "تظليل", englishName: "Hatch", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "ملء منطقة بنمط تظليل. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["hatch", "fill", "pattern"] },
    { id: "ac09", type: "shortcut", shortcutType: "cmd", shortcut: "T → Enter", arabicName: "كتابة نص متعدد", englishName: "Multiline Text", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "إضافة نص متعدد الأسطر. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["text", "mtext", "write"] },
    { id: "ac10", type: "shortcut", shortcutType: "cmd", shortcut: "DT → Enter", arabicName: "كتابة نص مفرد", englishName: "Single Line Text", program: "AutoCAD", category: "AutoCAD", subCategory: "الرسم", description: "إضافة نص في سطر واحد. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["text", "dtext", "single"] },

    // --- أوامر التعديل (Modify Commands) ---
    { id: "ac11", type: "shortcut", shortcutType: "cmd", shortcut: "E → Enter", arabicName: "حذف كائن", englishName: "Erase", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "حذف الكائنات المحددة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["erase", "delete", "remove"] },
    { id: "ac12", type: "shortcut", shortcutType: "cmd", shortcut: "CO → Enter", arabicName: "نسخ كائن", englishName: "Copy", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "نسخ الكائنات المحددة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["copy", "duplicate"] },
    { id: "ac13", type: "shortcut", shortcutType: "cmd", shortcut: "M → Enter", arabicName: "تحريك كائن", englishName: "Move", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "نقل الكائنات لموضع جديد. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["move", "displace"] },
    { id: "ac14", type: "shortcut", shortcutType: "cmd", shortcut: "RO → Enter", arabicName: "تدوير كائن", englishName: "Rotate", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "تدوير الكائنات حول نقطة محددة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["rotate", "turn", "angle"] },
    { id: "ac15", type: "shortcut", shortcutType: "cmd", shortcut: "SC → Enter", arabicName: "مقياس / تغيير الحجم", englishName: "Scale", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "تكبير أو تصغير الكائنات بنسبة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["scale", "resize", "size"] },
    { id: "ac16", type: "shortcut", shortcutType: "cmd", shortcut: "MI → Enter", arabicName: "انعكاس مرآوي", englishName: "Mirror", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "عكس الكائنات حول محور. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["mirror", "flip", "reflect"] },
    { id: "ac17", type: "shortcut", shortcutType: "cmd", shortcut: "AR → Enter", arabicName: "مصفوفة", englishName: "Array", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "تكرار الكائنات بشكل مصفوفي. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["array", "repeat", "pattern"] },
    { id: "ac18", type: "shortcut", shortcutType: "cmd", shortcut: "O → Enter", arabicName: "إزاحة", englishName: "Offset", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "إنشاء نسخة موازية بمسافة محددة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["offset", "parallel", "distance"] },
    { id: "ac19", type: "shortcut", shortcutType: "cmd", shortcut: "TR → Enter", arabicName: "قطع", englishName: "Trim", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "قطع جزء من الخطوط عند حدودها. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["trim", "cut", "clip"] },
    { id: "ac20", type: "shortcut", shortcutType: "cmd", shortcut: "EX → Enter", arabicName: "تمديد", englishName: "Extend", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "تمديد الخطوط حتى حد محدد. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["extend", "lengthen"] },
    { id: "ac21", type: "shortcut", shortcutType: "cmd", shortcut: "F → Enter", arabicName: "تخميل الزاوية", englishName: "Fillet", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "إنشاء زاوية مستديرة بين خطين. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["fillet", "round", "corner"] },
    { id: "ac22", type: "shortcut", shortcutType: "cmd", shortcut: "CHA → Enter", arabicName: "قطع الزاوية", englishName: "Chamfer", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "إنشاء قطع مستقيم بين خطين. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["chamfer", "bevel", "corner"] },
    { id: "ac23", type: "shortcut", shortcutType: "cmd", shortcut: "X → Enter", arabicName: "تفجير كائن", englishName: "Explode", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "تفكيك الكتل والأشكال المركبة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["explode", "break", "decompose"] },
    { id: "ac24", type: "shortcut", shortcutType: "cmd", shortcut: "PE → Enter", arabicName: "تعديل خط متعدد", englishName: "Polyline Edit", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "تحرير الخطوط المتعددة وتحويلها. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["pedit", "edit", "poly"] },
    { id: "ac25", type: "shortcut", shortcutType: "cmd", shortcut: "S → Enter", arabicName: "تمديد أو تقليص", englishName: "Stretch", program: "AutoCAD", category: "AutoCAD", subCategory: "التعديل", description: "تمديد أجزاء من الرسم مع إبقاء الاتصال. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["stretch", "lengthen", "modify"] },

    // --- البُعد والقياس (Dimension) ---
    { id: "ac26", type: "shortcut", shortcutType: "cmd", shortcut: "DLI → Enter", arabicName: "بُعد خطي", englishName: "Linear Dimension", program: "AutoCAD", category: "AutoCAD", subCategory: "الأبعاد", description: "إضافة بُعد أفقي أو رأسي. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["dimension", "linear", "measure"] },
    { id: "ac27", type: "shortcut", shortcutType: "cmd", shortcut: "DAL → Enter", arabicName: "بُعد مائل", englishName: "Aligned Dimension", program: "AutoCAD", category: "AutoCAD", subCategory: "الأبعاد", description: "إضافة بُعد موازٍ للكائن المقاس. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["aligned", "dimension"] },
    { id: "ac28", type: "shortcut", shortcutType: "cmd", shortcut: "DRA → Enter", arabicName: "بُعد نصف القطر", englishName: "Radius Dimension", program: "AutoCAD", category: "AutoCAD", subCategory: "الأبعاد", description: "قياس نصف قطر الدائرة أو القوس. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["radius", "dimension"] },
    { id: "ac29", type: "shortcut", shortcutType: "cmd", shortcut: "DAN → Enter", arabicName: "بُعد الزاوية", englishName: "Angular Dimension", program: "AutoCAD", category: "AutoCAD", subCategory: "الأبعاد", description: "قياس الزاوية بين خطين. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["angle", "dimension"] },
    { id: "ac30", type: "shortcut", shortcutType: "cmd", shortcut: "DI → Enter", arabicName: "قياس المسافة", englishName: "Distance", program: "AutoCAD", category: "AutoCAD", subCategory: "الأبعاد", description: "قياس المسافة بين نقطتين. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["distance", "measure"] },

    // --- العرض والتنقل (View & Navigation) ---
    { id: "ac31", type: "shortcut", shortcutType: "cmd", shortcut: "Z + E → Enter", arabicName: "ضبط العرض للكل", englishName: "Zoom Extents", program: "AutoCAD", category: "AutoCAD", subCategory: "العرض", description: "تكبير العرض ليشمل كامل الرسم. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["zoom", "extents", "fit"] },
    { id: "ac32", type: "shortcut", shortcutType: "cmd", shortcut: "Z + A → Enter", arabicName: "ضبط العرض الكل", englishName: "Zoom All", program: "AutoCAD", category: "AutoCAD", subCategory: "العرض", description: "عرض كل محتوى الرسمة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["zoom", "all", "view"] },
    { id: "ac33", type: "shortcut", shortcutType: "cmd", shortcut: "Z + W → Enter", arabicName: "تكبير منطقة", englishName: "Zoom Window", program: "AutoCAD", category: "AutoCAD", subCategory: "العرض", description: "تكبير منطقة محددة بإطار. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["zoom", "window"] },
    { id: "ac34", type: "shortcut", shortcutType: "cmd", shortcut: "Z + P → Enter", arabicName: "العرض السابق", englishName: "Zoom Previous", program: "AutoCAD", category: "AutoCAD", subCategory: "العرض", description: "العودة لمستوى التكبير السابق. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["zoom", "previous", "back"] },
    { id: "ac35", type: "shortcut", shortcutType: "cmd", shortcut: "P → Enter", arabicName: "تحريك العرض", englishName: "Pan", program: "AutoCAD", category: "AutoCAD", subCategory: "العرض", description: "تحريك عرض اللوحة بدون تغيير التكبير. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["pan", "scroll", "move"] },
    { id: "ac36", type: "shortcut", shortcutType: "combo", shortcut: "Ctrl + Shift + H", arabicName: "إخفاء عناصر التنسيق", englishName: "Toggle Clean Screen", program: "AutoCAD", category: "AutoCAD", subCategory: "العرض", description: "تفعيل وضع الشاشة النظيفة.", keywords: ["clean", "hide", "fullscreen"] },
    { id: "ac37", type: "shortcut", shortcutType: "combo", shortcut: "F2", arabicName: "نافذة النص", englishName: "Text Window", program: "AutoCAD", category: "AutoCAD", subCategory: "العرض", description: "فتح نافذة سجل الأوامر الموسعة.", keywords: ["text", "log", "command"] },

    // --- الطبقات والخصائص (Layers & Properties) ---
    { id: "ac38", type: "shortcut", shortcutType: "cmd", shortcut: "LA → Enter", arabicName: "إدارة الطبقات", englishName: "Layer Manager", program: "AutoCAD", category: "AutoCAD", subCategory: "الطبقات", description: "فتح مدير الطبقات. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["layer", "manage"] },
    { id: "ac39", type: "shortcut", shortcutType: "cmd", shortcut: "MO → Enter", arabicName: "خصائص الكائن", englishName: "Properties", program: "AutoCAD", category: "AutoCAD", subCategory: "الطبقات", description: "فتح نافذة خصائص الكائن المحدد. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["properties", "settings", "object"] },
    { id: "ac40", type: "shortcut", shortcutType: "cmd", shortcut: "MA → Enter", arabicName: "مطابقة الخصائص", englishName: "Match Properties", program: "AutoCAD", category: "AutoCAD", subCategory: "الطبقات", description: "نقل خصائص كائن لكائنات أخرى. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["match", "copy", "properties"] },

    // --- عام ---
    { id: "ac41", type: "shortcut", shortcutType: "combo", shortcut: "Ctrl + Z", arabicName: "تراجع", englishName: "Undo", program: "AutoCAD", category: "AutoCAD", subCategory: "عام", description: "التراجع عن آخر أمر.", keywords: ["undo", "back"] },
    { id: "ac42", type: "shortcut", shortcutType: "combo", shortcut: "Ctrl + Y", arabicName: "إعادة", englishName: "Redo", program: "AutoCAD", category: "AutoCAD", subCategory: "عام", description: "إعادة الأمر الملغى.", keywords: ["redo", "forward"] },
    { id: "ac43", type: "shortcut", shortcutType: "combo", shortcut: "Ctrl + S", arabicName: "حفظ", englishName: "Save", program: "AutoCAD", category: "AutoCAD", subCategory: "عام", description: "حفظ الملف الحالي.", keywords: ["save"] },
    { id: "ac44", type: "shortcut", shortcutType: "combo", shortcut: "Esc", arabicName: "إلغاء الأمر", englishName: "Cancel Command", program: "AutoCAD", category: "AutoCAD", subCategory: "عام", description: "إلغاء الأمر الجاري.", keywords: ["cancel", "escape", "stop"] },
    { id: "ac45", type: "shortcut", shortcutType: "combo", shortcut: "F8", arabicName: "وضع المتعامد", englishName: "Ortho Mode", program: "AutoCAD", category: "AutoCAD", subCategory: "عام", description: "تقييد الرسم للاتجاهات الأفقية والرأسية.", keywords: ["ortho", "perpendicular", "straight"] },
    { id: "ac46", type: "shortcut", shortcutType: "combo", shortcut: "F3", arabicName: "الالتقاط بالكائن", englishName: "Object Snap", program: "AutoCAD", category: "AutoCAD", subCategory: "عام", description: "تفعيل وضع الالتقاط الذكي بنقاط الكائنات.", keywords: ["snap", "osnap", "lock"] },
    { id: "ac47", type: "shortcut", shortcutType: "cmd", shortcut: "G → Enter", arabicName: "تجميع", englishName: "Group", program: "AutoCAD", category: "AutoCAD", subCategory: "عام", description: "تجميع كائنات في وحدة واحدة. اكتب الأمر في Command Bar ثم اضغط Enter.", keywords: ["group", "combine"] },
];
